name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint poetry
    - name: Analysing the code with pylint
      run: |
        set -x
        pylint $(find src/ -name "*.py" | xargs)
    - name: Check via Poetry
      run: poetry check
    - name: Test Via Unittest Module
      run: |
        set -x
        poetry run python3 -m unittest test/test.py
